#ifndef LIGHT_SABER_PARAMS
#define LIGHT_SABER_PARAMS

/* Change this for different security strengths */
#define LIGHT_SABER_L 2 /* LightSaber */
//#define LIGHT_SABER_L 3 /* Saber */
// #define LIGHT_SABER_L 4 /* FireSaber */

/* Don't change anything below this line */
#if LIGHT_SABER_L == 2
#define LIGHT_SABER_MU 10
#define LIGHT_SABER_ET 3
#elif LIGHT_SABER_L == 3
#define LIGHT_SABER_MU 8
#define LIGHT_SABER_ET 4
#elif LIGHT_SABER_L == 4
#define LIGHT_SABER_MU 6
#define LIGHT_SABER_ET 6
#endif

#define LIGHT_SABER_EQ 13
#define LIGHT_SABER_EP 10
#define LIGHT_SABER_N 256

#define LIGHT_SABER_SEEDBYTES 32
#define LIGHT_SABER_NOISE_SEEDBYTES 32
#define LIGHT_SABER_KEYBYTES 32
#define LIGHT_SABER_HASHBYTES 32

#define LIGHT_SABER_POLYCOINBYTES (LIGHT_SABER_MU * LIGHT_SABER_N / 8)

#define LIGHT_SABER_POLYBYTES (LIGHT_SABER_EQ * LIGHT_SABER_N / 8)
#define LIGHT_SABER_POLYVECBYTES (LIGHT_SABER_L * LIGHT_SABER_POLYBYTES)

#define LIGHT_SABER_POLYCOMPRESSEDBYTES (LIGHT_SABER_EP * LIGHT_SABER_N / 8)
#define LIGHT_SABER_POLYVECCOMPRESSEDBYTES (LIGHT_SABER_L * LIGHT_SABER_POLYCOMPRESSEDBYTES)

#define LIGHT_SABER_SCALEBYTES_KEM (LIGHT_SABER_ET * LIGHT_SABER_N / 8)

#define LIGHT_SABER_INDCPA_PUBLICKEYBYTES (LIGHT_SABER_POLYVECCOMPRESSEDBYTES + LIGHT_SABER_SEEDBYTES)
#define LIGHT_SABER_INDCPA_SECRETKEYBYTES (LIGHT_SABER_POLYVECBYTES)

#define LIGHT_SABER_PUBLICKEYBYTES (LIGHT_SABER_INDCPA_PUBLICKEYBYTES)
#define LIGHT_SABER_SECRETKEYBYTES (LIGHT_SABER_INDCPA_SECRETKEYBYTES + LIGHT_SABER_INDCPA_PUBLICKEYBYTES + LIGHT_SABER_HASHBYTES + LIGHT_SABER_KEYBYTES)

#define LIGHT_SABER_BYTES_CCA_DEC (LIGHT_SABER_POLYVECCOMPRESSEDBYTES + LIGHT_SABER_SCALEBYTES_KEM)

#define LIGHT_SABER_CIPHERTEXTBYTES (LIGHT_SABER_BYTES_CCA_DEC)

#endif
