// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handshake.proto

#include "handshake.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_handshake_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DSPublicKey_handshake_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_handshake_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DSResult_handshake_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_handshake_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_KEMPublicKey_handshake_2eproto;
namespace neptune {
namespace packets {
class DSPublicKeyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DSPublicKey> _instance;
} _DSPublicKey_default_instance_;
class DSResultDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DSResult> _instance;
} _DSResult_default_instance_;
class KEMPublicKeyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<KEMPublicKey> _instance;
} _KEMPublicKey_default_instance_;
class HandshakeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Handshake> _instance;
} _Handshake_default_instance_;
}  // namespace packets
}  // namespace neptune
static void InitDefaultsscc_info_DSPublicKey_handshake_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::neptune::packets::_DSPublicKey_default_instance_;
    new (ptr) ::neptune::packets::DSPublicKey();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DSPublicKey_handshake_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DSPublicKey_handshake_2eproto}, {}};

static void InitDefaultsscc_info_DSResult_handshake_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::neptune::packets::_DSResult_default_instance_;
    new (ptr) ::neptune::packets::DSResult();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DSResult_handshake_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DSResult_handshake_2eproto}, {}};

static void InitDefaultsscc_info_Handshake_handshake_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::neptune::packets::_Handshake_default_instance_;
    new (ptr) ::neptune::packets::Handshake();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_Handshake_handshake_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_Handshake_handshake_2eproto}, {
      &scc_info_KEMPublicKey_handshake_2eproto.base,
      &scc_info_DSPublicKey_handshake_2eproto.base,
      &scc_info_DSResult_handshake_2eproto.base,}};

static void InitDefaultsscc_info_KEMPublicKey_handshake_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::neptune::packets::_KEMPublicKey_default_instance_;
    new (ptr) ::neptune::packets::KEMPublicKey();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_KEMPublicKey_handshake_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_KEMPublicKey_handshake_2eproto}, {}};

namespace neptune {
namespace packets {
bool eDS_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> eDS_strings[8] = {};

static const char eDS_names[] =
  "DILITHIUM_1024x768"
  "DILITHIUM_1280x1024"
  "DILITHIUM_1536x1280"
  "ED25519"
  "ED448"
  "FALCON_1024"
  "FALCON_512"
  "_INVALID_DS_";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry eDS_entries[] = {
  { {eDS_names + 0, 18}, 3 },
  { {eDS_names + 18, 19}, 4 },
  { {eDS_names + 37, 19}, 5 },
  { {eDS_names + 56, 7}, 1 },
  { {eDS_names + 63, 5}, 2 },
  { {eDS_names + 68, 11}, 7 },
  { {eDS_names + 79, 10}, 6 },
  { {eDS_names + 89, 12}, 0 },
};

static const int eDS_entries_by_number[] = {
  7, // 0 -> _INVALID_DS_
  3, // 1 -> ED25519
  4, // 2 -> ED448
  0, // 3 -> DILITHIUM_1024x768
  1, // 4 -> DILITHIUM_1280x1024
  2, // 5 -> DILITHIUM_1536x1280
  6, // 6 -> FALCON_512
  5, // 7 -> FALCON_1024
};

const std::string& eDS_Name(
    eDS value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          eDS_entries,
          eDS_entries_by_number,
          8, eDS_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      eDS_entries,
      eDS_entries_by_number,
      8, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     eDS_strings[idx].get();
}
bool eDS_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eDS* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      eDS_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<eDS>(int_value);
  }
  return success;
}
bool eHashing_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 4:
    case 7:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> eHashing_strings[4] = {};

static const char eHashing_names[] =
  "BLAKE3_256"
  "SHA2_256"
  "SHA3_256"
  "_INVALID_H_";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry eHashing_entries[] = {
  { {eHashing_names + 0, 10}, 7 },
  { {eHashing_names + 10, 8}, 1 },
  { {eHashing_names + 18, 8}, 4 },
  { {eHashing_names + 26, 11}, 0 },
};

static const int eHashing_entries_by_number[] = {
  3, // 0 -> _INVALID_H_
  1, // 1 -> SHA2_256
  2, // 4 -> SHA3_256
  0, // 7 -> BLAKE3_256
};

const std::string& eHashing_Name(
    eHashing value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          eHashing_entries,
          eHashing_entries_by_number,
          4, eHashing_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      eHashing_entries,
      eHashing_entries_by_number,
      4, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     eHashing_strings[idx].get();
}
bool eHashing_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eHashing* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      eHashing_entries, 4, name, &int_value);
  if (success) {
    *value = static_cast<eHashing>(int_value);
  }
  return success;
}
bool eKEM_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> eKEM_strings[13] = {};

static const char eKEM_names[] =
  "FireSABER"
  "KYBER_1024"
  "KYBER_1024_90s"
  "KYBER_512"
  "KYBER_512_90s"
  "KYBER_768"
  "KYBER_768_90s"
  "LightSABER"
  "NTRU"
  "SABER"
  "X25519"
  "X448"
  "_INVALID_KEM_";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry eKEM_entries[] = {
  { {eKEM_names + 0, 9}, 11 },
  { {eKEM_names + 9, 10}, 5 },
  { {eKEM_names + 19, 14}, 8 },
  { {eKEM_names + 33, 9}, 3 },
  { {eKEM_names + 42, 13}, 6 },
  { {eKEM_names + 55, 9}, 4 },
  { {eKEM_names + 64, 13}, 7 },
  { {eKEM_names + 77, 10}, 9 },
  { {eKEM_names + 87, 4}, 12 },
  { {eKEM_names + 91, 5}, 10 },
  { {eKEM_names + 96, 6}, 1 },
  { {eKEM_names + 102, 4}, 2 },
  { {eKEM_names + 106, 13}, 0 },
};

static const int eKEM_entries_by_number[] = {
  12, // 0 -> _INVALID_KEM_
  10, // 1 -> X25519
  11, // 2 -> X448
  3, // 3 -> KYBER_512
  5, // 4 -> KYBER_768
  1, // 5 -> KYBER_1024
  4, // 6 -> KYBER_512_90s
  6, // 7 -> KYBER_768_90s
  2, // 8 -> KYBER_1024_90s
  7, // 9 -> LightSABER
  9, // 10 -> SABER
  0, // 11 -> FireSABER
  8, // 12 -> NTRU
};

const std::string& eKEM_Name(
    eKEM value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          eKEM_entries,
          eKEM_entries_by_number,
          13, eKEM_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      eKEM_entries,
      eKEM_entries_by_number,
      13, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     eKEM_strings[idx].get();
}
bool eKEM_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eKEM* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      eKEM_entries, 13, name, &int_value);
  if (success) {
    *value = static_cast<eKEM>(int_value);
  }
  return success;
}

// ===================================================================

class DSPublicKey::_Internal {
 public:
};

DSPublicKey::DSPublicKey(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:neptune.packets.DSPublicKey)
}
DSPublicKey::DSPublicKey(const DSPublicKey& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_key().empty()) {
    key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_key(), 
      GetArena());
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:neptune.packets.DSPublicKey)
}

void DSPublicKey::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DSPublicKey_handshake_2eproto.base);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
}

DSPublicKey::~DSPublicKey() {
  // @@protoc_insertion_point(destructor:neptune.packets.DSPublicKey)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void DSPublicKey::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DSPublicKey::ArenaDtor(void* object) {
  DSPublicKey* _this = reinterpret_cast< DSPublicKey* >(object);
  (void)_this;
}
void DSPublicKey::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DSPublicKey::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DSPublicKey& DSPublicKey::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DSPublicKey_handshake_2eproto.base);
  return *internal_default_instance();
}


void DSPublicKey::Clear() {
// @@protoc_insertion_point(message_clear_start:neptune.packets.DSPublicKey)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmpty();
  type_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* DSPublicKey::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .neptune.packets.eDS type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::neptune::packets::eDS>(val));
        } else goto handle_unusual;
        continue;
      // bytes key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DSPublicKey::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:neptune.packets.DSPublicKey)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .neptune.packets.eDS type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // bytes key = 2;
  if (this->key().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:neptune.packets.DSPublicKey)
  return target;
}

size_t DSPublicKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:neptune.packets.DSPublicKey)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_key());
  }

  // .neptune.packets.eDS type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DSPublicKey::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const DSPublicKey*>(
      &from));
}

void DSPublicKey::MergeFrom(const DSPublicKey& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:neptune.packets.DSPublicKey)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {
    _internal_set_key(from._internal_key());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void DSPublicKey::CopyFrom(const DSPublicKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:neptune.packets.DSPublicKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DSPublicKey::IsInitialized() const {
  return true;
}

void DSPublicKey::InternalSwap(DSPublicKey* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  key_.Swap(&other->key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(type_, other->type_);
}

std::string DSPublicKey::GetTypeName() const {
  return "neptune.packets.DSPublicKey";
}


// ===================================================================

class DSResult::_Internal {
 public:
};

DSResult::DSResult(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:neptune.packets.DSResult)
}
DSResult::DSResult(const DSResult& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  result_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_result().empty()) {
    result_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_result(), 
      GetArena());
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:neptune.packets.DSResult)
}

void DSResult::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DSResult_handshake_2eproto.base);
  result_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
}

DSResult::~DSResult() {
  // @@protoc_insertion_point(destructor:neptune.packets.DSResult)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void DSResult::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  result_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DSResult::ArenaDtor(void* object) {
  DSResult* _this = reinterpret_cast< DSResult* >(object);
  (void)_this;
}
void DSResult::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DSResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DSResult& DSResult::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DSResult_handshake_2eproto.base);
  return *internal_default_instance();
}


void DSResult::Clear() {
// @@protoc_insertion_point(message_clear_start:neptune.packets.DSResult)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_.ClearToEmpty();
  type_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* DSResult::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .neptune.packets.eDS type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::neptune::packets::eDS>(val));
        } else goto handle_unusual;
        continue;
      // bytes result = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_result();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DSResult::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:neptune.packets.DSResult)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .neptune.packets.eDS type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // bytes result = 2;
  if (this->result().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:neptune.packets.DSResult)
  return target;
}

size_t DSResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:neptune.packets.DSResult)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes result = 2;
  if (this->result().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_result());
  }

  // .neptune.packets.eDS type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DSResult::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const DSResult*>(
      &from));
}

void DSResult::MergeFrom(const DSResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:neptune.packets.DSResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result().size() > 0) {
    _internal_set_result(from._internal_result());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void DSResult::CopyFrom(const DSResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:neptune.packets.DSResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DSResult::IsInitialized() const {
  return true;
}

void DSResult::InternalSwap(DSResult* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  result_.Swap(&other->result_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(type_, other->type_);
}

std::string DSResult::GetTypeName() const {
  return "neptune.packets.DSResult";
}


// ===================================================================

class KEMPublicKey::_Internal {
 public:
};

KEMPublicKey::KEMPublicKey(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:neptune.packets.KEMPublicKey)
}
KEMPublicKey::KEMPublicKey(const KEMPublicKey& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_key().empty()) {
    key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_key(), 
      GetArena());
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:neptune.packets.KEMPublicKey)
}

void KEMPublicKey::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_KEMPublicKey_handshake_2eproto.base);
  key_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
}

KEMPublicKey::~KEMPublicKey() {
  // @@protoc_insertion_point(destructor:neptune.packets.KEMPublicKey)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void KEMPublicKey::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  key_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void KEMPublicKey::ArenaDtor(void* object) {
  KEMPublicKey* _this = reinterpret_cast< KEMPublicKey* >(object);
  (void)_this;
}
void KEMPublicKey::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void KEMPublicKey::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const KEMPublicKey& KEMPublicKey::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_KEMPublicKey_handshake_2eproto.base);
  return *internal_default_instance();
}


void KEMPublicKey::Clear() {
// @@protoc_insertion_point(message_clear_start:neptune.packets.KEMPublicKey)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmpty();
  type_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* KEMPublicKey::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .neptune.packets.eKEM type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::neptune::packets::eKEM>(val));
        } else goto handle_unusual;
        continue;
      // bytes key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_key();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* KEMPublicKey::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:neptune.packets.KEMPublicKey)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .neptune.packets.eKEM type = 1;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // bytes key = 2;
  if (this->key().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_key(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:neptune.packets.KEMPublicKey)
  return target;
}

size_t KEMPublicKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:neptune.packets.KEMPublicKey)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_key());
  }

  // .neptune.packets.eKEM type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KEMPublicKey::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const KEMPublicKey*>(
      &from));
}

void KEMPublicKey::MergeFrom(const KEMPublicKey& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:neptune.packets.KEMPublicKey)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {
    _internal_set_key(from._internal_key());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void KEMPublicKey::CopyFrom(const KEMPublicKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:neptune.packets.KEMPublicKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KEMPublicKey::IsInitialized() const {
  return true;
}

void KEMPublicKey::InternalSwap(KEMPublicKey* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  key_.Swap(&other->key_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(type_, other->type_);
}

std::string KEMPublicKey::GetTypeName() const {
  return "neptune.packets.KEMPublicKey";
}


// ===================================================================

class Handshake::_Internal {
 public:
};

Handshake::Handshake(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena),
  kem_keys_(arena),
  ds_keys_(arena),
  ds_results_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:neptune.packets.Handshake)
}
Handshake::Handshake(const Handshake& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      kem_keys_(from.kem_keys_),
      ds_keys_(from.ds_keys_),
      ds_results_(from.ds_results_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  salt_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_salt().empty()) {
    salt_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_salt(), 
      GetArena());
  }
  version_ = from.version_;
  // @@protoc_insertion_point(copy_constructor:neptune.packets.Handshake)
}

void Handshake::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Handshake_handshake_2eproto.base);
  salt_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  version_ = 0u;
}

Handshake::~Handshake() {
  // @@protoc_insertion_point(destructor:neptune.packets.Handshake)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void Handshake::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  salt_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Handshake::ArenaDtor(void* object) {
  Handshake* _this = reinterpret_cast< Handshake* >(object);
  (void)_this;
}
void Handshake::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Handshake::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Handshake& Handshake::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Handshake_handshake_2eproto.base);
  return *internal_default_instance();
}


void Handshake::Clear() {
// @@protoc_insertion_point(message_clear_start:neptune.packets.Handshake)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  kem_keys_.Clear();
  ds_keys_.Clear();
  ds_results_.Clear();
  salt_.ClearToEmpty();
  version_ = 0u;
  _internal_metadata_.Clear<std::string>();
}

const char* Handshake::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .neptune.packets.KEMPublicKey kem_keys = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_kem_keys(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .neptune.packets.DSPublicKey ds_keys = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ds_keys(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .neptune.packets.DSResult ds_results = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ds_results(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // bytes salt = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_salt();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Handshake::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:neptune.packets.Handshake)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 version = 1;
  if (this->version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_version(), target);
  }

  // repeated .neptune.packets.KEMPublicKey kem_keys = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_kem_keys_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_kem_keys(i), target, stream);
  }

  // repeated .neptune.packets.DSPublicKey ds_keys = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ds_keys_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_ds_keys(i), target, stream);
  }

  // repeated .neptune.packets.DSResult ds_results = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ds_results_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_ds_results(i), target, stream);
  }

  // bytes salt = 5;
  if (this->salt().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_salt(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:neptune.packets.Handshake)
  return target;
}

size_t Handshake::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:neptune.packets.Handshake)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .neptune.packets.KEMPublicKey kem_keys = 2;
  total_size += 1UL * this->_internal_kem_keys_size();
  for (const auto& msg : this->kem_keys_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .neptune.packets.DSPublicKey ds_keys = 3;
  total_size += 1UL * this->_internal_ds_keys_size();
  for (const auto& msg : this->ds_keys_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .neptune.packets.DSResult ds_results = 4;
  total_size += 1UL * this->_internal_ds_results_size();
  for (const auto& msg : this->ds_results_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // bytes salt = 5;
  if (this->salt().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_salt());
  }

  // uint32 version = 1;
  if (this->version() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_version());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Handshake::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const Handshake*>(
      &from));
}

void Handshake::MergeFrom(const Handshake& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:neptune.packets.Handshake)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  kem_keys_.MergeFrom(from.kem_keys_);
  ds_keys_.MergeFrom(from.ds_keys_);
  ds_results_.MergeFrom(from.ds_results_);
  if (from.salt().size() > 0) {
    _internal_set_salt(from._internal_salt());
  }
  if (from.version() != 0) {
    _internal_set_version(from._internal_version());
  }
}

void Handshake::CopyFrom(const Handshake& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:neptune.packets.Handshake)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Handshake::IsInitialized() const {
  return true;
}

void Handshake::InternalSwap(Handshake* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  kem_keys_.InternalSwap(&other->kem_keys_);
  ds_keys_.InternalSwap(&other->ds_keys_);
  ds_results_.InternalSwap(&other->ds_results_);
  salt_.Swap(&other->salt_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(version_, other->version_);
}

std::string Handshake::GetTypeName() const {
  return "neptune.packets.Handshake";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace packets
}  // namespace neptune
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::neptune::packets::DSPublicKey* Arena::CreateMaybeMessage< ::neptune::packets::DSPublicKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::neptune::packets::DSPublicKey >(arena);
}
template<> PROTOBUF_NOINLINE ::neptune::packets::DSResult* Arena::CreateMaybeMessage< ::neptune::packets::DSResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::neptune::packets::DSResult >(arena);
}
template<> PROTOBUF_NOINLINE ::neptune::packets::KEMPublicKey* Arena::CreateMaybeMessage< ::neptune::packets::KEMPublicKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::neptune::packets::KEMPublicKey >(arena);
}
template<> PROTOBUF_NOINLINE ::neptune::packets::Handshake* Arena::CreateMaybeMessage< ::neptune::packets::Handshake >(Arena* arena) {
  return Arena::CreateMessageInternal< ::neptune::packets::Handshake >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
