#ifndef PARAMS_H
#define PARAMS_H

/* Change this for different security strengths */
// #define FIRE_SABER_L 2 /* LightSaber */
#define FIRE_SABER_L 3 /* Saber */
// #define FIRE_SABER_L 4 /* FireSaber */

/* Don't change anything below this line */
#if FIRE_SABER_L == 2
#define FIRE_SABER_MU 10
#define FIRE_SABER_ET 3
#elif FIRE_SABER_L == 3
#define FIRE_SABER_MU 8
#define FIRE_SABER_ET 4
#elif FIRE_SABER_L == 4
#define FIRE_SABER_MU 6
#define FIRE_SABER_ET 6
#endif

#define FIRE_SABER_EQ 13
#define FIRE_SABER_EP 10
#define FIRE_SABER_N 256

#define FIRE_SABER_SEEDBYTES 32
#define FIRE_SABER_NOISE_SEEDBYTES 32
#define FIRE_SABER_KEYBYTES 32
#define FIRE_SABER_HASHBYTES 32

#define FIRE_SABER_POLYCOINBYTES (FIRE_SABER_MU * FIRE_SABER_N / 8)

#define FIRE_SABER_POLYBYTES (FIRE_SABER_EQ * FIRE_SABER_N / 8)
#define FIRE_SABER_POLYVECBYTES (FIRE_SABER_L * FIRE_SABER_POLYBYTES)

#define FIRE_SABER_POLYCOMPRESSEDBYTES (FIRE_SABER_EP * FIRE_SABER_N / 8)
#define FIRE_SABER_POLYVECCOMPRESSEDBYTES (FIRE_SABER_L * FIRE_SABER_POLYCOMPRESSEDBYTES)

#define FIRE_SABER_SCALEBYTES_KEM (FIRE_SABER_ET * FIRE_SABER_N / 8)

#define FIRE_SABER_INDCPA_PUBLICKEYBYTES (FIRE_SABER_POLYVECCOMPRESSEDBYTES + FIRE_SABER_SEEDBYTES)
#define FIRE_SABER_INDCPA_SECRETKEYBYTES (FIRE_SABER_POLYVECBYTES)

#define FIRE_SABER_PUBLICKEYBYTES (FIRE_SABER_INDCPA_PUBLICKEYBYTES)
#define FIRE_SABER_SECRETKEYBYTES (FIRE_SABER_INDCPA_SECRETKEYBYTES + FIRE_SABER_INDCPA_PUBLICKEYBYTES + FIRE_SABER_HASHBYTES + FIRE_SABER_KEYBYTES)

#define FIRE_SABER_BYTES_CCA_DEC (FIRE_SABER_POLYVECCOMPRESSEDBYTES + FIRE_SABER_SCALEBYTES_KEM)

#define FIRE_SABER_CIPHERTEXTBYTES (FIRE_SABER_BYTES_CCA_DEC)

#endif
